replicaCount: 2

image:
  repository: ecommerceacrregistry.azurecr.io/ecommerce-api
  pullPolicy: IfNotPresent
  tag: 6e1ac450cd8c0bfa18a0e89440278066b96576f1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: 
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  PORT: "3000"
  NODE_ENV: "production"

monitoring:
  enabled: true
